# Generated by rust2rpm 10
# * demo-hack is not packaged
%bcond_with check
%global debug_package %{nil}

%global crate proc-macro-hack

Name:           rust-%{crate}
Version:        0.5.11
Release:        2%{?dist}
Summary:        Procedural macros in expression position

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/proc-macro-hack
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Procedural macros in expression position.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.11-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Tue Nov 19 2019 Josh Stone <jistone@redhat.com> - 0.5.11-1
- Update to 0.5.11

* Sun Aug 25 14:29:10 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.9-1
- Update to 0.5.9

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.8-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jul 06 11:21:59 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.8-1
- Update to 0.5.8

* Thu May 09 09:03:38 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.7-1
- Update to 0.5.7

* Thu May 09 08:24:11 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.6-1
- Update to 0.5.6

* Tue Apr 16 2019 Josh Stone <jistone@redhat.com> - 0.5.5-1
- Update to 0.5.5

* Wed Mar 13 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.5.4-1
- Initial package
